namespace ContactsApp.Views
{
      public partial class AddContacts : ContentPage
    {
        public AddContacts()
        {
            InitializeComponent(); // This should be automatically generated by the XAML compiler
        }

        private void BtnCancel_Clicked(object sender, EventArgs e)
        {
            Shell.Current.GoToAsync((".."));
        }
    }}